#%RAML 1.0
title: HOTEL SEARCH API

/search: 
  get: 
    queryParameters:
      location:
        description: "Location to search"
        example: london
        required: true
        type: string
    responses:
      200: 
        body:
          application/json:
            type: | 
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example:
              {
                "message": "Hello world"
              }
/buy:
  get:
    responses:
      200: 
        body:
          application/json:
            type: | 
              {
                "title": "Purchase response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                  "status": {
                    "type": "number"
                  }
                }
              }
            example:
              {
                "message": "Bought!"
              }         
